/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.acme.integration;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MailingAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1709453518562463152L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MailingAddress\",\"namespace\":\"org.acme.integration\",\"fields\":[{\"name\":\"street\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"city\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"state_prov\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"country\",\"type\":\"string\",\"default\":\"NONE\"},{\"name\":\"zip\",\"type\":\"string\",\"default\":\"NONE\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MailingAddress> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MailingAddress> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MailingAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MailingAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MailingAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MailingAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MailingAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MailingAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MailingAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence street;
  private java.lang.CharSequence city;
  private java.lang.CharSequence state_prov;
  private java.lang.CharSequence country;
  private java.lang.CharSequence zip;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MailingAddress() {}

  /**
   * All-args constructor.
   * @param street The new value for street
   * @param city The new value for city
   * @param state_prov The new value for state_prov
   * @param country The new value for country
   * @param zip The new value for zip
   */
  public MailingAddress(java.lang.CharSequence street, java.lang.CharSequence city, java.lang.CharSequence state_prov, java.lang.CharSequence country, java.lang.CharSequence zip) {
    this.street = street;
    this.city = city;
    this.state_prov = state_prov;
    this.country = country;
    this.zip = zip;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return street;
    case 1: return city;
    case 2: return state_prov;
    case 3: return country;
    case 4: return zip;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: street = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: state_prov = (java.lang.CharSequence)value$; break;
    case 3: country = (java.lang.CharSequence)value$; break;
    case 4: zip = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }


  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state_prov' field.
   * @return The value of the 'state_prov' field.
   */
  public java.lang.CharSequence getStateProv() {
    return state_prov;
  }


  /**
   * Sets the value of the 'state_prov' field.
   * @param value the value to set.
   */
  public void setStateProv(java.lang.CharSequence value) {
    this.state_prov = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'zip' field.
   * @return The value of the 'zip' field.
   */
  public java.lang.CharSequence getZip() {
    return zip;
  }


  /**
   * Sets the value of the 'zip' field.
   * @param value the value to set.
   */
  public void setZip(java.lang.CharSequence value) {
    this.zip = value;
  }

  /**
   * Creates a new MailingAddress RecordBuilder.
   * @return A new MailingAddress RecordBuilder
   */
  public static org.acme.integration.MailingAddress.Builder newBuilder() {
    return new org.acme.integration.MailingAddress.Builder();
  }

  /**
   * Creates a new MailingAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MailingAddress RecordBuilder
   */
  public static org.acme.integration.MailingAddress.Builder newBuilder(org.acme.integration.MailingAddress.Builder other) {
    if (other == null) {
      return new org.acme.integration.MailingAddress.Builder();
    } else {
      return new org.acme.integration.MailingAddress.Builder(other);
    }
  }

  /**
   * Creates a new MailingAddress RecordBuilder by copying an existing MailingAddress instance.
   * @param other The existing instance to copy.
   * @return A new MailingAddress RecordBuilder
   */
  public static org.acme.integration.MailingAddress.Builder newBuilder(org.acme.integration.MailingAddress other) {
    if (other == null) {
      return new org.acme.integration.MailingAddress.Builder();
    } else {
      return new org.acme.integration.MailingAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for MailingAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MailingAddress>
    implements org.apache.avro.data.RecordBuilder<MailingAddress> {

    private java.lang.CharSequence street;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state_prov;
    private java.lang.CharSequence country;
    private java.lang.CharSequence zip;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.acme.integration.MailingAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state_prov)) {
        this.state_prov = data().deepCopy(fields()[2].schema(), other.state_prov);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.zip)) {
        this.zip = data().deepCopy(fields()[4].schema(), other.zip);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing MailingAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(org.acme.integration.MailingAddress other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.street)) {
        this.street = data().deepCopy(fields()[0].schema(), other.street);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state_prov)) {
        this.state_prov = data().deepCopy(fields()[2].schema(), other.state_prov);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zip)) {
        this.zip = data().deepCopy(fields()[4].schema(), other.zip);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }


    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.street = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder clearStreet() {
      street = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state_prov' field.
      * @return The value.
      */
    public java.lang.CharSequence getStateProv() {
      return state_prov;
    }


    /**
      * Sets the value of the 'state_prov' field.
      * @param value The value of 'state_prov'.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder setStateProv(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state_prov = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state_prov' field has been set.
      * @return True if the 'state_prov' field has been set, false otherwise.
      */
    public boolean hasStateProv() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state_prov' field.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder clearStateProv() {
      state_prov = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.country = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder clearCountry() {
      country = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'zip' field.
      * @return The value.
      */
    public java.lang.CharSequence getZip() {
      return zip;
    }


    /**
      * Sets the value of the 'zip' field.
      * @param value The value of 'zip'.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder setZip(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.zip = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'zip' field has been set.
      * @return True if the 'zip' field has been set, false otherwise.
      */
    public boolean hasZip() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'zip' field.
      * @return This builder.
      */
    public org.acme.integration.MailingAddress.Builder clearZip() {
      zip = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MailingAddress build() {
      try {
        MailingAddress record = new MailingAddress();
        record.street = fieldSetFlags()[0] ? this.street : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state_prov = fieldSetFlags()[2] ? this.state_prov : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.country = fieldSetFlags()[3] ? this.country : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.zip = fieldSetFlags()[4] ? this.zip : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MailingAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<MailingAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MailingAddress>
    READER$ = (org.apache.avro.io.DatumReader<MailingAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.street);

    out.writeString(this.city);

    out.writeString(this.state_prov);

    out.writeString(this.country);

    out.writeString(this.zip);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.state_prov = in.readString(this.state_prov instanceof Utf8 ? (Utf8)this.state_prov : null);

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

      this.zip = in.readString(this.zip instanceof Utf8 ? (Utf8)this.zip : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);
          break;

        case 1:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 2:
          this.state_prov = in.readString(this.state_prov instanceof Utf8 ? (Utf8)this.state_prov : null);
          break;

        case 3:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        case 4:
          this.zip = in.readString(this.zip instanceof Utf8 ? (Utf8)this.zip : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










